import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        Task1 _1st = new Task1();
        Task2 _2nd = new Task2();
        Task3 _3rd = new Task3();
        Task4 _4th = new Task4();
        Task4n1 _4n1th = new Task4n1();
        Task5 _5th = new Task5();
        Task6 _6th = new Task6();
        Task7 _7th = new Task7();
        Task8 _8th = new Task8();
        Task9 _9th = new Task9();
        Task10 _10th = new Task10();
        Task11 _11th = new Task11();
        Task12 _12th = new Task12();
        Task13 _13th = new Task13();
        Task14 _14th = new Task14();
        Task15 _15th = new Task15();
        Task16 _16th = new Task16();
        Task17 _17th = new Task17();
        Task18 _18th = new Task18();
        Task19 _19th = new Task19();
        Task20 _20th = new Task20();
        Task21 _21th = new Task21();
        Task22 _22th = new Task22();
        Task23 _23th = new Task23();
        _23th.doThing();
    }
}
